export const hierarchyData = [
  {
    id: 7,
    type: "Use Case Section",
    level: 1,
    name: "Test_1 Section",
    blt: "blt1",
    description: "long desc",
    children: [
      {
        id: 8,
        type: "Use Case Line Item",
        level: 2,
        name: "Test_1 Line Item",
        blt: "",
        description: "long desc",
        children: [
          {
            id: 6,
            type: "Use Case Data Element",
            level: 3,
            name: "Test_1 Data Element 1",
            blt: "",
            description: "long desc",
          },
          {
            id: 6,
            type: "Use Case Data Element",
            level: 3,
            name: "Test_1 Data Element 2",
            blt: "",
            description: "long desc",
          },
        ],
      },
    ],
  },
  {
    id: 7,
    type: "Use Case Section",
    level: 1,
    name: "Test_1 Section",
    blt: "blt1",
    description: "long desc",
    children: [
      {
        id: 8,
        type: "Use Case Line Item",
        level: 2,
        name: "Test_1 Line Item",
        blt: "",
        description: "long desc",
        children: [
          {
            id: 6,
            type: "Use Case Data Element",
            level: 3,
            name: "Test_1 Data Element 1",
            blt: "",
            description: "long desc",
          },
          {
            id: 6,
            type: "Use Case Data Element",
            level: 3,
            name: "Test_1 Data Element 2",
            blt: "",
            description: "long desc",
          },
        ],
      },
      {
        id: 8,
        type: "Use Case Line Item",
        level: 2,
        name: "Test_2 Line Item",
        blt: "",
        description: "long desc",
        children: [
          {
            id: 6,
            type: "Use Case Data Element",
            level: 3,
            name: "Test_2 Data Element 1",
            blt: "",
            description: "long desc",
          },
          {
            id: 6,
            type: "Use Case Data Element",
            level: 3,
            name: "Test_2 Data Element 2",
            blt: "",
            description: "long desc",
          },
        ],
      },
    ],
  },
];

export const columns = [
  {
    title: "",
    id: "col-exp-col-icon",
  },
  {
    title: "Element Name",
    id: "name",
  },
  {
    title: "Element Type",
    id: "type",
  },
  {
    title: "Description",
    id: "comments",
  },
  {
    title: "Business Logic Text",
    id: "blt",
  },
];

export const flatRowData = [
  {
    rowId: "section-1",
    id: 8,
    type: "Use Case Section",
    level: 1,
    name: "Test_1 Section",
    blt: "blt1",
    description: "long desc",
    noOfChildren: 3,
    rowClass: "row-section-1",
    expanded: false,
    price: "30$",
    comments:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    status: "DRAFT",
  },
  {
    rowId: "section-1-lineItem-1",
    id: 9,
    type: "Use Case Line Item",
    level: 2,
    name: "Test_1 Line Item",
    blt: "",
    description: "long desc",
    noOfChildren: 2,
    rowClass: "row-section-1 lineItem-1",
    expanded: false,
    price: "15$",
    comments: "consectetur adipiscing elit,labore et dolore magna aliqua",
    status: "PENDING_REVIEW",
  },
  {
    rowId: "section-1-lineItem-1-dataElement-1",
    rowClass: "row-section-1 lineItem-1 dataElement-1",
    id: 6,
    type: "Use Case Data Element",
    level: 3,
    name: "Test_1 Data Element 1",
    blt: "",
    description: "long desc",
    price: "30$",
    comments:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit,labore et dolore magna aliqua",
    status: "DRAFT",
  },
  {
    rowId: "section-1-lineItem-1-dataElement-2",
    rowClass: "row-section-1 lineItem-1 dataElement-2",
    id: 7,
    type: "Use Case Data Element",
    level: 3,
    name: "Test_1 Data Element 2",
    blt: "",
    description: "long desc",
    price: "10$",
    comments:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua,sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    status: "DRAFT",
  },
  {
    rowId: "section-2",
    id: 11,
    type: "Use Case Section",
    level: 1,
    name: "Test_2 Section",
    blt: "blt1",
    description: "long desc",
    noOfChildren: 2,
    rowClass: "row-section-2",
    expanded: false,
    price: "10$",
    comments:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit,labore et dolore magna aliqua",
    status: "DRAFT",
  },
  {
    rowId: "section-2-lineItem-2",
    rowClass: "row-section-2 lineItem-2",
    id: 12,
    noOfChildren: 1,
    type: "Use Case Line Item",
    level: 2,
    name: "Test_2 Line Item",
    blt: "",
    description: "long desc",
    expanded: false,
    price: "10$",
    comments:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit,labore et dolore magna aliqua",
    status: "DRAFT",
  },
  {
    rowId: "section-2-lineItem-2-dataElement-1",
    rowClass: "row-section-2 lineItem-2 dataElement-1",
    id: 10,
    type: "Use Case Data Element",
    level: 3,
    name: "Test_2 Data Element 1",
    blt: "",
    description: "long desc",
    price: "10$",
    comments:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit,labore et dolore magna aliqua",
    status: "DRAFT",
  },
];
